//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS_Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string tour_name { get; set; }
        public int id_city { get; set; }
        public System.DateTime initDate { get; set; }
        public System.DateTime toDate { get; set; }
        public int limit { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
